Added embeds for all basic bot commands
S4DS-IEM/S4DS-Bot pull request #6
Opened 2021-08-14 17:30 UTC by sdk2k01

@Dsantra92 
all basic bot commands and error messages give errors in vibrant embeds.

2021-08-14 17:47 UTC, Dsantra92 requested changes
There are some minor changes required for maintaining style consistency in the codebase. I have suggested changes only in some of the lines, but the changes are to be made for all lines with similar styling problems.

2021-08-14 17:47 UTC, Dsantra92 commented on src/cogs/basic.py
> +status = cycle(['arXiv','Kaggle','redditAPI'])
status = cycle([ 'arXiv', 'Kaggle', 'redditAPI' ])

2021-08-14 17:47 UTC, Dsantra92 commented on src/cogs/basic.py
> +        embed=discord.Embed(title="Ping",
Give a space before and after `=`

2021-08-14 17:47 UTC, Dsantra92 commented on src/cogs/basic.py
> +        color=discord.Color.teal())
spacing issue with `=` and `,`

2021-08-14 17:47 UTC, Dsantra92 commented on src/cogs/basic.py
> +            #await ctx.send('Please specify an amount of messages to be deleted!')
spacing issue `=`

2021-08-15 04:44 UTC, sdk2k01 commented
Updated PR.
The changes requested have been made. Space discrepancies are removed and comments are added.
<details>
<summary>A brief preview of the changes</summary>
<img width="862" alt="Screenshot 2021-08-15 at 10 03 50 AM" src="https://user-images.githubusercontent.com/77383234/129467388-9442c7f4-5b8d-454e-81c4-28ac64f53add.png">
</details>

2021-08-15 05:30 UTC, merged

2021-08-15 05:30 UTC, Dsantra92 commented
Bhery Kull deer!!